### ISSUE TITLE
Confusion around who to get help from

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/platform-support-slackbot#34]
I've noticed many people don't know who to get help from when asking a support question. These are the options:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/10993987/192546589-dee34344-89ca-49fb-97a6-f97e72cdaf49.png">

Here are some recent snippets from confused individuals:
> Hi folks and sorry if I selected the wrong team

> I couldn’t figure out what request categories to put this in.

> I apologize if I chose the wrong support team

> I couldn’t figure out what request categories to put this in, sorry.

> I'm not sure who to get help from

> Not sure which team is equipped to handle this.

Ideas:
* Could the team names be more descriptive?
* Could we say something to the effect of, "make your best guess. we'll reassign the team if needed"?
* One person asking for support wanted an "I don't know" category (not sure if we should do that, just passing on the feedback).
* Would it help to define the team names and their responsibilities on the platform website?
* Not sure how this will all change with the new matrix-style teams, but some of those teams won't exist anymore.

**Comment by powellkerry** [comment]
@rmtolmach with the team re-org I think all of these concerns are being addressed. See the changes coming next week [here](https://vfs.atlassian.net/wiki/spaces/SRE/pages/2370142243/Team+Re-org+Slack+Support-bot+Adjustments).

let me know if there is anything that hasn't been addressed, or needs a bit more thought.

**Comment by rmtolmach** [comment]
oh, nice! yeah that document seems to cover it all. I'll close this issue.
